# Model run parameters
rgt_boolean: False
data_dir: '../data_uploads'
results_dir: '../model_results'

# General model assumptions
num_years: 2
num_regions: 4
i_rate: 0.05
annualize_years_cap: 20
annualize_years_storage: 10

# Capital cost assumptions
onshore_cost_mw: 1.584e6
offshore_cost_mw: 3.754e6
solar_cost_mw: 1.9e6
battery_cost_mwh: 36e3
battery_cost_mw: 500e3
h2_cost_mwh: 8e3
h2_cost_mw: 1.1e6
gt_cost_mw: [7.44e5, 7.44e5, 1.071e6, 1.071e6]

# Variable cost assumptions
gt_startup_cost_mw: 69
hq_cost_mwh: [20, 0, 70, 0]
netload_cost_mwh: [22.83, 31.91, 28.59, 28.59]

# Existing capacity assumptions
onshore_wind_limit_mw: [32402, 4376, 0, 0]
solar_limit_mw: [1e100, 1e100, 10400, 13600]
hq_limit_mw: [1500, 0, 0, 0]
gt_current_cap_mw: [3655.2, 6332, 8848, 3971]

# Storage assumptions
battery_eff: 0.948
h2_eff: 0.6
self_discharge: 0.001
battery_p2e_ratio_range: [0.25, 8]
h2_p2e_ratio_range: [0, 1e100]

# EV assumptions
ev_charging_p2e_ratio: 1/6
ev_eff: 0.948
ev_hours_start: 19
ev_charging_hours: 24
ev_charging_method: 'flexible' # or fixed
ev_load_dist: [0.370449679, 0.177730193, 0.243040685, 0.208779443]

# Other various assumptions
trans_eff: 0.97
reserve_req: 1.17
hqch_capacity_factor: 0.9

# Existing capacity and transmission cost assumptions
cap_market_cost_mw_yr: [27640, 27640, 104600, 104600]  # $/MW-yr
existing_trans_load_mwh: [74.533e6, 50.829e6, 18.400e6]
existing_trans_cost_mwh: [15.6, 21.8, 41.0]

# Regional nuclear and hydro generation
nuc_gen_mw: [3019, 0, 0, 0]
hydro_gen_mw: [2727.9, 269.1, 0, 0]
flex_hydro_cap_mw: [1443, 1187, 0, 0]
instate_hydro_cost_mwh: 18
instate_nuc_cost_mwh: 75

# Gurobi solver parameters
feasibility_tol: 0.01
solver_method: -1