# Model run parameters
model_config: 0 # 0: LCT + Elec. specified, GHG returned; 1: LCT + GHG. specified, Elec. returned;
#                 2: LCT + GHG. specified, Elec. returned;
rgt_boolean: False
data_dir: '../data_uploads'
results_dir: '../model_results'
nuclear_boolean: False
h2_boolean: False
solve_model: True

# General model assumptions
num_years: 1
num_regions: 4
i_rate: 0.05
annualize_years_cap: 20
annualize_years_storage: 10

# Capital cost assumptions
onshore_cost_mw: 1.992e6
#onshore_cost_low_mw: 1.698e6
offshore_cost_mw: 3.583e6
#offshore_cost_low_mw: 2.256e6
solar_cost_mw: [2e6, 2e6, 2.511e6, 2.511e6]
battery_cost_mw: 500e3
battery_cost_mwh: 36e3
h2_cost_mw: [1.1e6, 1.1e6, 1.583e6, 1.583e6]
h2_cost_mwh: [350, 14e3, 14e3, 14e3]
new_gt_cost_mw: [7.44e5, 7.44e5, 1.071e6, 1.071e6]

# O&M + startup cost assumptions
onshore_fixed_om_cost_mwyr: 20e3
offshore_fixed_om_cost_mwyr: 38e3
solar_fixed_om_cost_mwyr: 10e3
h2_fixed_om_cost_mwyr: 48.87e3
new_gt_fixed_om_cost_mwyr: 7.01e3
new_gt_var_om_cost_mwh: 11.02
gt_startup_cost_mw: 69

# Variable fuel cost assumptions
hq_cost_mwh: [20, 0, 70, 0]
natgas_cost_mmbtu: [2.89, 4.04, 3.62, 3.62]
mmbtu_per_mwh: 3.412

# Capacity assumptions
onshore_wind_limit_mw: [32402, 4376, 0, 0]
offshore_wind_limit_mw: 57938
solar_limit_mw: [1e100, 1e100, 10400, 13600]
hq_limit_mw: [1500, 0, 0, 0]
existing_gt_cap_mw: [3655.2, 6332, 8848, 3971]

# Storage assumptions
battery_eff: 0.948
h2_eff: 0.6
self_discharge: 0.001
battery_p2e_ratio_range: [0.25, 8]
h2_p2e_ratio_range: [0, 1e100]

# Heating assumptions
# heating_load_dist: [0.5866352, 0.09192513, 0.20545611, 0.11598355]
# heating_max_cap: 7308

# EV assumptions
ev_charging_p2e_ratio: 0.166666667
ev_eff: 0.948
ev_hours_start: 19
ev_charging_hours: 12
ev_charging_method: 'flexible' # or fixed
ev_load_dist: [0.370449679, 0.177730193, 0.243040685, 0.208779443]
ev_max_cap: 6660

# Other various assumptions
trans_loss: 0.03
reserve_req: 1.17
hqch_capacity_factor: 0.9
new_gt_eff: 0.399
existing_gt_eff: 0.419
nominal_trans_cost_mwh: 0.01

# Existing capacity and transmission cost assumptions
cap_market_cost_mw_yr: [27640, 27640, 104600, 104600]  # $/MW-yr
existing_load_mwh: [76.848e6, 52.296e6, 19.072e6] # first value is for combined upstate regions 1 + 2
existing_trans_cost_mwh: [16, 22.1, 43.9]
existing_dist_cost_mwh:  [36.6, 94.7, 73.9]

# Regional nuclear and hydro generation and costs
nuc_gen_mw: [3019, 0, 0, 0]
nuc_cap_mw: [3381, 0, 0, 0]
hydro_gen_mw: [2727.9, 269.1, 0, 0]
hydro_cap_mw: [4350, 1187, 0, 0]
flex_hydro_cap_mw: [1443, 1187, 0, 0]
instate_hydro_cost_mwh: [18, 18, 0, 0]
instate_nuc_cost_mwh:   [46.31, 0, 0, 0]


# Gurobi solver parameters
feasibility_tol: 0.005
solver_method: -1